/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { RouterHistory } from "@stencil-community/router";
export namespace Components {
    interface AppEventPlannerBioItem {
        "Bio": string;
        "CompanyName": string;
        "EventPlannerId": number;
        "FirstName": string;
        "LastName": string;
    }
    interface AppEventPlannerItem {
        "Bio": string;
        "CompanyName": string;
        "EventPlannerId": number;
        "FirstName": string;
        "HeadshotAltText": string;
        "HeadshotURL": string;
        "LastName": string;
    }
    interface AppFooter {
    }
    interface AppFooterLegalLinks {
        "footerLegalLinksHeader": HTMLElement;
        "footerLegalLinksItems": HTMLElement;
    }
    interface AppFooterNavigation {
        "footerNavigationHeader": HTMLElement;
        "footerNavigationItems": HTMLElement;
    }
    interface AppHeader {
        "backgroundClass": string;
    }
    interface AppLeadershipTeamItem {
        "Bio": string;
        "Color": string;
        "FirstName": string;
        "HeadshotAltText": string;
        "HeadshotURL": string;
        "JobTitle": string;
        "LastName": string;
    }
    interface AppLoginButton {
    }
    interface AppNavigation {
    }
    interface AppRoot {
    }
    interface AppTestimonialCarousel {
    }
    interface PageAboutUs {
        "leadershipTeamMembers": HTMLElement;
    }
    interface PageCodeOfConduct {
    }
    interface PageCookiePolicy {
    }
    interface PageDashboard {
        "history": RouterHistory;
    }
    interface PageDemo {
        "companyAddressTypeOptions": HTMLElement;
        "companyEmailAddressTypeOptions": HTMLElement;
        "companyPhoneNumberTypeOptions": HTMLElement;
        "companySocialMediaTypeOptions": HTMLElement;
        "countryOptions": HTMLElement;
        "history": RouterHistory;
        "personAddressTypeOptions": HTMLElement;
        "personCompanyAddressTypeOptions": HTMLElement;
        "personCompanyEmailAddressTypeOptions": HTMLElement;
        "personCompanyPhoneNumberTypeOptions": HTMLElement;
        "personCompanySocialMediaTypeOptions": HTMLElement;
        "personEmailAddressTypeOptions": HTMLElement;
        "personPhoneNumberTypeOptions": HTMLElement;
        "personSocialMediaTypeOptions": HTMLElement;
        "prefixesOptions": HTMLElement;
        "pronounOptions": HTMLElement;
        "suffixesOptions": HTMLElement;
    }
    interface PageDestinations {
        "history": RouterHistory;
    }
    interface PageDirectory {
        "history": RouterHistory;
    }
    interface PageEventPlanners {
        "eventPlanners": HTMLElement;
    }
    interface PageHome {
        "foundingPlannerLogos": HTMLElement;
    }
    interface PageJoin {
        "history": RouterHistory;
    }
    interface PageLogin {
    }
    interface PageLoginRedirect {
    }
    interface PageLogout {
    }
    interface PageNotFound {
    }
    interface PagePrivacyPolicy {
    }
    interface PageTermsOfService {
    }
}
declare global {
    interface HTMLAppEventPlannerBioItemElement extends Components.AppEventPlannerBioItem, HTMLStencilElement {
    }
    var HTMLAppEventPlannerBioItemElement: {
        prototype: HTMLAppEventPlannerBioItemElement;
        new (): HTMLAppEventPlannerBioItemElement;
    };
    interface HTMLAppEventPlannerItemElement extends Components.AppEventPlannerItem, HTMLStencilElement {
    }
    var HTMLAppEventPlannerItemElement: {
        prototype: HTMLAppEventPlannerItemElement;
        new (): HTMLAppEventPlannerItemElement;
    };
    interface HTMLAppFooterElement extends Components.AppFooter, HTMLStencilElement {
    }
    var HTMLAppFooterElement: {
        prototype: HTMLAppFooterElement;
        new (): HTMLAppFooterElement;
    };
    interface HTMLAppFooterLegalLinksElement extends Components.AppFooterLegalLinks, HTMLStencilElement {
    }
    var HTMLAppFooterLegalLinksElement: {
        prototype: HTMLAppFooterLegalLinksElement;
        new (): HTMLAppFooterLegalLinksElement;
    };
    interface HTMLAppFooterNavigationElement extends Components.AppFooterNavigation, HTMLStencilElement {
    }
    var HTMLAppFooterNavigationElement: {
        prototype: HTMLAppFooterNavigationElement;
        new (): HTMLAppFooterNavigationElement;
    };
    interface HTMLAppHeaderElement extends Components.AppHeader, HTMLStencilElement {
    }
    var HTMLAppHeaderElement: {
        prototype: HTMLAppHeaderElement;
        new (): HTMLAppHeaderElement;
    };
    interface HTMLAppLeadershipTeamItemElement extends Components.AppLeadershipTeamItem, HTMLStencilElement {
    }
    var HTMLAppLeadershipTeamItemElement: {
        prototype: HTMLAppLeadershipTeamItemElement;
        new (): HTMLAppLeadershipTeamItemElement;
    };
    interface HTMLAppLoginButtonElement extends Components.AppLoginButton, HTMLStencilElement {
    }
    var HTMLAppLoginButtonElement: {
        prototype: HTMLAppLoginButtonElement;
        new (): HTMLAppLoginButtonElement;
    };
    interface HTMLAppNavigationElement extends Components.AppNavigation, HTMLStencilElement {
    }
    var HTMLAppNavigationElement: {
        prototype: HTMLAppNavigationElement;
        new (): HTMLAppNavigationElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLAppTestimonialCarouselElement extends Components.AppTestimonialCarousel, HTMLStencilElement {
    }
    var HTMLAppTestimonialCarouselElement: {
        prototype: HTMLAppTestimonialCarouselElement;
        new (): HTMLAppTestimonialCarouselElement;
    };
    interface HTMLPageAboutUsElement extends Components.PageAboutUs, HTMLStencilElement {
    }
    var HTMLPageAboutUsElement: {
        prototype: HTMLPageAboutUsElement;
        new (): HTMLPageAboutUsElement;
    };
    interface HTMLPageCodeOfConductElement extends Components.PageCodeOfConduct, HTMLStencilElement {
    }
    var HTMLPageCodeOfConductElement: {
        prototype: HTMLPageCodeOfConductElement;
        new (): HTMLPageCodeOfConductElement;
    };
    interface HTMLPageCookiePolicyElement extends Components.PageCookiePolicy, HTMLStencilElement {
    }
    var HTMLPageCookiePolicyElement: {
        prototype: HTMLPageCookiePolicyElement;
        new (): HTMLPageCookiePolicyElement;
    };
    interface HTMLPageDashboardElement extends Components.PageDashboard, HTMLStencilElement {
    }
    var HTMLPageDashboardElement: {
        prototype: HTMLPageDashboardElement;
        new (): HTMLPageDashboardElement;
    };
    interface HTMLPageDemoElement extends Components.PageDemo, HTMLStencilElement {
    }
    var HTMLPageDemoElement: {
        prototype: HTMLPageDemoElement;
        new (): HTMLPageDemoElement;
    };
    interface HTMLPageDestinationsElement extends Components.PageDestinations, HTMLStencilElement {
    }
    var HTMLPageDestinationsElement: {
        prototype: HTMLPageDestinationsElement;
        new (): HTMLPageDestinationsElement;
    };
    interface HTMLPageDirectoryElement extends Components.PageDirectory, HTMLStencilElement {
    }
    var HTMLPageDirectoryElement: {
        prototype: HTMLPageDirectoryElement;
        new (): HTMLPageDirectoryElement;
    };
    interface HTMLPageEventPlannersElement extends Components.PageEventPlanners, HTMLStencilElement {
    }
    var HTMLPageEventPlannersElement: {
        prototype: HTMLPageEventPlannersElement;
        new (): HTMLPageEventPlannersElement;
    };
    interface HTMLPageHomeElement extends Components.PageHome, HTMLStencilElement {
    }
    var HTMLPageHomeElement: {
        prototype: HTMLPageHomeElement;
        new (): HTMLPageHomeElement;
    };
    interface HTMLPageJoinElement extends Components.PageJoin, HTMLStencilElement {
    }
    var HTMLPageJoinElement: {
        prototype: HTMLPageJoinElement;
        new (): HTMLPageJoinElement;
    };
    interface HTMLPageLoginElement extends Components.PageLogin, HTMLStencilElement {
    }
    var HTMLPageLoginElement: {
        prototype: HTMLPageLoginElement;
        new (): HTMLPageLoginElement;
    };
    interface HTMLPageLoginRedirectElement extends Components.PageLoginRedirect, HTMLStencilElement {
    }
    var HTMLPageLoginRedirectElement: {
        prototype: HTMLPageLoginRedirectElement;
        new (): HTMLPageLoginRedirectElement;
    };
    interface HTMLPageLogoutElement extends Components.PageLogout, HTMLStencilElement {
    }
    var HTMLPageLogoutElement: {
        prototype: HTMLPageLogoutElement;
        new (): HTMLPageLogoutElement;
    };
    interface HTMLPageNotFoundElement extends Components.PageNotFound, HTMLStencilElement {
    }
    var HTMLPageNotFoundElement: {
        prototype: HTMLPageNotFoundElement;
        new (): HTMLPageNotFoundElement;
    };
    interface HTMLPagePrivacyPolicyElement extends Components.PagePrivacyPolicy, HTMLStencilElement {
    }
    var HTMLPagePrivacyPolicyElement: {
        prototype: HTMLPagePrivacyPolicyElement;
        new (): HTMLPagePrivacyPolicyElement;
    };
    interface HTMLPageTermsOfServiceElement extends Components.PageTermsOfService, HTMLStencilElement {
    }
    var HTMLPageTermsOfServiceElement: {
        prototype: HTMLPageTermsOfServiceElement;
        new (): HTMLPageTermsOfServiceElement;
    };
    interface HTMLElementTagNameMap {
        "app-event-planner-bio-item": HTMLAppEventPlannerBioItemElement;
        "app-event-planner-item": HTMLAppEventPlannerItemElement;
        "app-footer": HTMLAppFooterElement;
        "app-footer-legal-links": HTMLAppFooterLegalLinksElement;
        "app-footer-navigation": HTMLAppFooterNavigationElement;
        "app-header": HTMLAppHeaderElement;
        "app-leadership-team-item": HTMLAppLeadershipTeamItemElement;
        "app-login-button": HTMLAppLoginButtonElement;
        "app-navigation": HTMLAppNavigationElement;
        "app-root": HTMLAppRootElement;
        "app-testimonial-carousel": HTMLAppTestimonialCarouselElement;
        "page-about-us": HTMLPageAboutUsElement;
        "page-code-of-conduct": HTMLPageCodeOfConductElement;
        "page-cookie-policy": HTMLPageCookiePolicyElement;
        "page-dashboard": HTMLPageDashboardElement;
        "page-demo": HTMLPageDemoElement;
        "page-destinations": HTMLPageDestinationsElement;
        "page-directory": HTMLPageDirectoryElement;
        "page-event-planners": HTMLPageEventPlannersElement;
        "page-home": HTMLPageHomeElement;
        "page-join": HTMLPageJoinElement;
        "page-login": HTMLPageLoginElement;
        "page-login-redirect": HTMLPageLoginRedirectElement;
        "page-logout": HTMLPageLogoutElement;
        "page-not-found": HTMLPageNotFoundElement;
        "page-privacy-policy": HTMLPagePrivacyPolicyElement;
        "page-terms-of-service": HTMLPageTermsOfServiceElement;
    }
}
declare namespace LocalJSX {
    interface AppEventPlannerBioItem {
        "Bio"?: string;
        "CompanyName"?: string;
        "EventPlannerId"?: number;
        "FirstName"?: string;
        "LastName"?: string;
        "onEventPlannerItemSelected"?: (event: CustomEvent<number>) => void;
    }
    interface AppEventPlannerItem {
        "Bio"?: string;
        "CompanyName"?: string;
        "EventPlannerId"?: number;
        "FirstName"?: string;
        "HeadshotAltText"?: string;
        "HeadshotURL"?: string;
        "LastName"?: string;
        "onEventPlannerItemSelected"?: (event: CustomEvent<number>) => void;
    }
    interface AppFooter {
    }
    interface AppFooterLegalLinks {
        "footerLegalLinksHeader"?: HTMLElement;
        "footerLegalLinksItems"?: HTMLElement;
    }
    interface AppFooterNavigation {
        "footerNavigationHeader"?: HTMLElement;
        "footerNavigationItems"?: HTMLElement;
    }
    interface AppHeader {
        "backgroundClass"?: string;
    }
    interface AppLeadershipTeamItem {
        "Bio"?: string;
        "Color"?: string;
        "FirstName"?: string;
        "HeadshotAltText"?: string;
        "HeadshotURL"?: string;
        "JobTitle"?: string;
        "LastName"?: string;
    }
    interface AppLoginButton {
    }
    interface AppNavigation {
    }
    interface AppRoot {
    }
    interface AppTestimonialCarousel {
    }
    interface PageAboutUs {
        "leadershipTeamMembers"?: HTMLElement;
    }
    interface PageCodeOfConduct {
    }
    interface PageCookiePolicy {
    }
    interface PageDashboard {
        "history"?: RouterHistory;
    }
    interface PageDemo {
        "companyAddressTypeOptions"?: HTMLElement;
        "companyEmailAddressTypeOptions"?: HTMLElement;
        "companyPhoneNumberTypeOptions"?: HTMLElement;
        "companySocialMediaTypeOptions"?: HTMLElement;
        "countryOptions"?: HTMLElement;
        "history"?: RouterHistory;
        "personAddressTypeOptions"?: HTMLElement;
        "personCompanyAddressTypeOptions"?: HTMLElement;
        "personCompanyEmailAddressTypeOptions"?: HTMLElement;
        "personCompanyPhoneNumberTypeOptions"?: HTMLElement;
        "personCompanySocialMediaTypeOptions"?: HTMLElement;
        "personEmailAddressTypeOptions"?: HTMLElement;
        "personPhoneNumberTypeOptions"?: HTMLElement;
        "personSocialMediaTypeOptions"?: HTMLElement;
        "prefixesOptions"?: HTMLElement;
        "pronounOptions"?: HTMLElement;
        "suffixesOptions"?: HTMLElement;
    }
    interface PageDestinations {
        "history"?: RouterHistory;
    }
    interface PageDirectory {
        "history"?: RouterHistory;
    }
    interface PageEventPlanners {
        "eventPlanners"?: HTMLElement;
    }
    interface PageHome {
        "foundingPlannerLogos"?: HTMLElement;
    }
    interface PageJoin {
        "history"?: RouterHistory;
    }
    interface PageLogin {
    }
    interface PageLoginRedirect {
    }
    interface PageLogout {
    }
    interface PageNotFound {
    }
    interface PagePrivacyPolicy {
    }
    interface PageTermsOfService {
    }
    interface IntrinsicElements {
        "app-event-planner-bio-item": AppEventPlannerBioItem;
        "app-event-planner-item": AppEventPlannerItem;
        "app-footer": AppFooter;
        "app-footer-legal-links": AppFooterLegalLinks;
        "app-footer-navigation": AppFooterNavigation;
        "app-header": AppHeader;
        "app-leadership-team-item": AppLeadershipTeamItem;
        "app-login-button": AppLoginButton;
        "app-navigation": AppNavigation;
        "app-root": AppRoot;
        "app-testimonial-carousel": AppTestimonialCarousel;
        "page-about-us": PageAboutUs;
        "page-code-of-conduct": PageCodeOfConduct;
        "page-cookie-policy": PageCookiePolicy;
        "page-dashboard": PageDashboard;
        "page-demo": PageDemo;
        "page-destinations": PageDestinations;
        "page-directory": PageDirectory;
        "page-event-planners": PageEventPlanners;
        "page-home": PageHome;
        "page-join": PageJoin;
        "page-login": PageLogin;
        "page-login-redirect": PageLoginRedirect;
        "page-logout": PageLogout;
        "page-not-found": PageNotFound;
        "page-privacy-policy": PagePrivacyPolicy;
        "page-terms-of-service": PageTermsOfService;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-event-planner-bio-item": LocalJSX.AppEventPlannerBioItem & JSXBase.HTMLAttributes<HTMLAppEventPlannerBioItemElement>;
            "app-event-planner-item": LocalJSX.AppEventPlannerItem & JSXBase.HTMLAttributes<HTMLAppEventPlannerItemElement>;
            "app-footer": LocalJSX.AppFooter & JSXBase.HTMLAttributes<HTMLAppFooterElement>;
            "app-footer-legal-links": LocalJSX.AppFooterLegalLinks & JSXBase.HTMLAttributes<HTMLAppFooterLegalLinksElement>;
            "app-footer-navigation": LocalJSX.AppFooterNavigation & JSXBase.HTMLAttributes<HTMLAppFooterNavigationElement>;
            "app-header": LocalJSX.AppHeader & JSXBase.HTMLAttributes<HTMLAppHeaderElement>;
            "app-leadership-team-item": LocalJSX.AppLeadershipTeamItem & JSXBase.HTMLAttributes<HTMLAppLeadershipTeamItemElement>;
            "app-login-button": LocalJSX.AppLoginButton & JSXBase.HTMLAttributes<HTMLAppLoginButtonElement>;
            "app-navigation": LocalJSX.AppNavigation & JSXBase.HTMLAttributes<HTMLAppNavigationElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "app-testimonial-carousel": LocalJSX.AppTestimonialCarousel & JSXBase.HTMLAttributes<HTMLAppTestimonialCarouselElement>;
            "page-about-us": LocalJSX.PageAboutUs & JSXBase.HTMLAttributes<HTMLPageAboutUsElement>;
            "page-code-of-conduct": LocalJSX.PageCodeOfConduct & JSXBase.HTMLAttributes<HTMLPageCodeOfConductElement>;
            "page-cookie-policy": LocalJSX.PageCookiePolicy & JSXBase.HTMLAttributes<HTMLPageCookiePolicyElement>;
            "page-dashboard": LocalJSX.PageDashboard & JSXBase.HTMLAttributes<HTMLPageDashboardElement>;
            "page-demo": LocalJSX.PageDemo & JSXBase.HTMLAttributes<HTMLPageDemoElement>;
            "page-destinations": LocalJSX.PageDestinations & JSXBase.HTMLAttributes<HTMLPageDestinationsElement>;
            "page-directory": LocalJSX.PageDirectory & JSXBase.HTMLAttributes<HTMLPageDirectoryElement>;
            "page-event-planners": LocalJSX.PageEventPlanners & JSXBase.HTMLAttributes<HTMLPageEventPlannersElement>;
            "page-home": LocalJSX.PageHome & JSXBase.HTMLAttributes<HTMLPageHomeElement>;
            "page-join": LocalJSX.PageJoin & JSXBase.HTMLAttributes<HTMLPageJoinElement>;
            "page-login": LocalJSX.PageLogin & JSXBase.HTMLAttributes<HTMLPageLoginElement>;
            "page-login-redirect": LocalJSX.PageLoginRedirect & JSXBase.HTMLAttributes<HTMLPageLoginRedirectElement>;
            "page-logout": LocalJSX.PageLogout & JSXBase.HTMLAttributes<HTMLPageLogoutElement>;
            "page-not-found": LocalJSX.PageNotFound & JSXBase.HTMLAttributes<HTMLPageNotFoundElement>;
            "page-privacy-policy": LocalJSX.PagePrivacyPolicy & JSXBase.HTMLAttributes<HTMLPagePrivacyPolicyElement>;
            "page-terms-of-service": LocalJSX.PageTermsOfService & JSXBase.HTMLAttributes<HTMLPageTermsOfServiceElement>;
        }
    }
}
